batch_size: 32
bilinear: true
dataset: train
dataset_folder: !!python/object/apply:pathlib.WindowsPath
- D:\
- Desktop
- Model
- HexMF-GNet
- data
- precipitation
- train_test_2020-2025_input-length_5_img-ahead_20_rain-threshold_20_norm.h5
default_save_path: !!python/object/apply:pathlib.WindowsPath
- D:\
- Desktop
- Model
- HexMF-GNet
- lightning
- 2020-2025
- HexMFG_batch-32_v1.0
disc_every_n_steps: 2
dropout: 0.5
epochs: 300
es_patience: 30
fast_dev_run: false
freq_loss_weight: 0.5
gpus: 1
high_freq_weight: 0.0
kernels_per_layer: 2
l: 1000000
learning_rate: 0.0001
lr_patience: 10
model: HexMFG
n_channels: 5
n_classes: 20
n_masks: 25
n_output_images: 20
num_input_images: 5
num_output_images: 20
reduction_ratio: 16
resume_from_checkpoint: null
runs: 1
structure_loss_weight: 0.0
temporal_growth_rate: 0.03
val_check_interval: null
valid_size: 0.1
visualize_losses: true
